spring:
    application:
        name:
            proyecto_gremio

    server:
        port:
            8081
    datasource:
        url:
            jdbc:mysql://localhost:3306/db_aventurero?createDatabaseIfNotExist=true
        username:
            root
        password:

        driverClassName:
            com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto:
                none
            show-sql:
                true
                
    flyway:
        enabled:
            true
        baseline-on-migrate:
            true