server:
  port: '0'

springdoc:
  api-docs:
    path: /gremios/api-docs

spring:
  application:
    name: gremios
  flyway:
    enabled: 'true'
    baseline-on-migrate: 'true'
  jpa:
    show-sql: 'true'
    
  profiles:
  active: dev

--- 

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_gremios_dev?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update 
    
--- 

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_gremios_test?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

---                                                             

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_gremios_prod?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: none