CREATE TABLE parties (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(70) NOT NULL,
    nivel INT NOT NULL DEFAULT 1,
    gremio_id INT NOT NULL
);

CREATE TABLE rangos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    nivel INT NOT NULL DEFAULT 1
);

CREATE TABLE reputaciones (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    nivel INT NOT NULL DEFAULT 0,
    faccion_id INT NOT NULL
);