server:
  port: 8081

spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: aventureros-service
              uri: lb://aventureros
              predicates:
                - Path=/api/v1/**

            - id: party-service
              uri: lb://party
              predicates:
                - Path=/api/v1/**
            
            - id: gremio-service
              uri: lb://gremio
              predicates:
                - Path=/api/v1/**